### ISSUE TITLE
Division by zero error

### ISSUE THREAD

**Issue by GianniM123** [GianniM123/ResearchInternship#5]
command: 
```
python3 ../algorithm/main.py \
--ref=../subjects/dtls/gnutls-3.6.7_all_cert_nreq.dot \
--upd=../subjects/dtls/nss-3.6.7_dhe_ecdhe_rsa.dot \
-t 0.8 -s z3 -l
```
Error:
```
dict["f-measure"] = (2 * dict["precision"] * dict["recall"]) / (dict["precision"] + dict["recall"])
ZeroDivisionError: float division by zero
```

**Comment by damascenodiego** [comment]
In the sklearn, there is a [special warning](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html#:~:text=UndefinedMetricWarning) for this case.

There is also [a parameter for setting a custom return value](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html#:~:text=Sample%20weights.-,zero_division,-%E2%80%9Cwarn%E2%80%9D%2C%200%20or). 

Maybe we could use a similar approach and **return zero by default** with a [warning message](https://docs.python.org/3/library/warnings.html) indicating this _UndefinedMetricWarning_.

**Comment by GianniM123** [comment]
> In the sklearn, there is a [special warning](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html#:~:text=UndefinedMetricWarning) for this case.
> 
> There is also [a parameter for setting a custom return value](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html#:~:text=zero_division%E2%80%9Cwarn%E2%80%9D%2C%200%20or%201%2C%20default%3D%E2%80%9Dwarn%E2%80%9D).
> 
> Maybe we could use a similar approach and **return zero by default** with a [warning message](https://docs.python.org/3/library/warnings.html) indicating this _UndefinedMetricWarning_.

Added the _UndefinedMetricWarning_ when recall and precision are 0
